blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'  # Define the app name for namespacing
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),  # URL for user signup
    path('login', views.login_view, name='login'),  # URL for user login
    path('logout/', views.logout_view, name='logout'),  # URL for user logout
    path('tags/<slug:tags_slug>/', views.list, name='list_by_tag'),  # URL for listing posts by tag
    path('', views.list, name='list'),  # Include the blog app's URLs
    path('<slug:slug>/<int:year>/<int:month>/<int:day>/', views.detail, name='detail'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),  # URL for liking a post
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# This is the main URL configuration for the Django project.
urlpatterns = [
    path('', include('blog.urls')),  # Include the blog app's URLs
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=10000)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=(('draft', 'Draft'), ('published', 'Published')), default='draft')
    tags = TaggableManager(blank=True)

    def __str__(self):
        return "{}-{}-{}".format(self.title, self.author.username, self.created_at.strftime('%Y-%m-%d %H:%M:%S'))
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={
            'slug': self.slug,
            'year': self.created_at.year,
            'month': self.created_at.month,
            'day': self.created_at.day
        })
    def active_comments(self):
        return self.comments.filter(is_active=True).order_by('-created_at')
    
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    
    def __str__(self):
        return "{}-{}-{}".format(self.post.title, self.author, self.created_at.strftime('%Y-%m-%d %H:%M:%S'))
    
class Like(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('post', 'user')  

    def __str__(self):
        return f"{self.user.username} liked {self.post.title}"

blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['comment']
        labels = {
            "comment": _("Comment"),
        }
        help_texts = {
            "comment": _("Write your comment here."),
        }
class SignUpForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            "username": _("Username"),
            "email": _("Email"),
            "password1": _("Password"),
            "password2": _("Confirm Password"),
        }
        help_texts = {
            "username": _("Enter a unique username."),
            "email": _("Enter a valid email address."),
            "password1": _("Enter your password."),
            "password2": _("Re-enter your password for confirmation."),
        }

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import models
from django.core.paginator import Paginator
from . import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
# Create your views here.
def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('blog:list')  # Redirect to the blog list after signup
    else:
        form = forms.SignUpForm()
    return render(request, 'blog/sign_up.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request,username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('blog:list')
    else:
        form = forms.LoginForm()
    return render(request, 'blog/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('blog:list')

def list(request,tags_slug=None):
    if tags_slug:
        posts = models.Post.objects.filter(status='published', tags__slug=tags_slug).order_by('-created_at')
    else:
        posts = models.Post.objects.filter(status='published').order_by('-created_at')
    paginator = Paginator(posts, 3)  # Show 3 posts per page
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    return render(request, 'blog/list.html', {'posts': posts})


def detail(request, slug, year, month, day):
    post = get_object_or_404(models.Post, created_at__year=year, created_at__month=month, created_at__day=day, slug=slug, status='published')
    if request.method == 'POST':
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.email = request.user.email
            comment.save()
            return render(request, 'blog/detail.html', {'post': post, 'comment_form': forms.CommentForm(), 'message': 'Your comment is awaiting approval.'})
    else:
        comment_form = forms.CommentForm()
    return render(request, 'blog/detail.html', {'post': post, 'comment_form': forms.CommentForm(), 'message': 'insert your comment below.'})
@login_required
def like_post(request, post_id):
    post = get_object_or_404(models.Post, id=post_id)
    like, created = models.Like.objects.get_or_create(post=post, user=request.user)
    if not created:
        like.delete()
        message = 'You unliked this post.'
    else:
        message = 'You liked this post.'
    return redirect('blog:detail', slug=post.slug, year=post.created_at.year, month=post.created_at.month, day=post.created_at.day)

blog/templates/blog/base.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Blog{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block extra_head %}{% endblock %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container">
            {% if not user.is_authenticated %}
            <li><a href="{% url 'blog:login' %}">login</a></li>
            <li><a href="{% url 'blog:sign_up' %}">Sign Up</a></li>
            {% else %}
            <li><a href="{% url 'blog:logout' %}">Logout</a></li>
            {% endif %}
             {% comment %} <li><a href="{% url 'blog:post_create' %}">Create Post</a></li> {% endcomment %}
            <a class="navbar-brand" href="{% url 'blog:list' %}">My Blog</a>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% block extra_js %}{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>By {{ post.author }} | {{ post.published_date }}</p>
    <div>
        {{ post.body|linebreaks }}
    </div>
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'blog:like_post' post.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">
            Like ({{ post.likes.count }})
        </button>
    </form>
    {% endif %}
    <h2>Comments({% total_comments post%})</h2>
    <ul>
        {% for comment in post.active_comments %}
            
            <li>
                <strong>{{ comment.author }}</strong> ({{ comment.created_at }}):<br>
                {{ comment.comment|linebreaks }}
            </li>
        {% empty %}
            <li>No comments yet.</li>
        {% endfor %}
            
        {% if user.is_authenticated %}
            <li>{{ message }}</li>
        <form method="post">
            {% csrf_token %}
            
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>
        {% endif %}
    </ul>
    <a href="{% url 'blog:list' %}">Back to posts</a>
{% endblock %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}Blog List
{% endblock %}

{% block content %}
    
    <h1>Blog Posts ({% total_posts %}) </h1>
    <ul> 
        {% for post in posts %}
            <li>
                <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
                <p>{{ post.published_date }}</p>
                <p>By {{ post.author }}</p>
                <p>
                    {% tag_or_tags post.tags.count %}{% for tag in post.tags.all %}
                        <a href="{% url 'blog:list_by_tag' tag.slug %}">{{ tag.name }}</a> 
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </li>
        {% empty %}
            <li>No posts available.</li>
        {% endfor %}
    </ul>
    <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
Login
{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

blog/templates/blog/sign_up.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
Sign Up
{% endblock %}

{% block content %}
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
    <p>Already have an account? <a href="{% url 'blog:login' %}">Login here</a>.</p>
{% endblock %}